repos:
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
        args: ["--exclude", "docs/"] # Exclude the 'docs' folder

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: end-of-file-fixer # ensure newline at end of file
        files: ^(?!docs/|\.gitignore|data/).*\.(?!pyx$).*$
      - id: check-yaml # verify yaml files
        files: ^(?!docs/).*$
      - id: check-toml # verify toml files
        files: ^(?!docs/).*$
      - id: check-added-large-files # prevent large files from being committed
        files: ^(?!data/).*$
      - id: check-merge-conflict # check for files that contain merge conflict strings
      - id: detect-private-key # check for private keys
      - id: debug-statements # check for debugger statements
        language_version: python3

  # - repo: https://github.com/codespell-project/codespell
  #   rev: v2.2.6
  #   hooks:
  #     - id: codespell
  #       args:
  #         - --skip=*.css,*.js,*.map,*.scss,*.svg,*.pyx
  #         - --ignore-words-list=magent,pres,roate

  - repo: https://github.com/PyCQA/isort
    rev: 6.0.0
    hooks:
      - id: isort
        args: ["--skip", "microvault/utils/*.pyx", "--profile", "black"]

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.19.1
    hooks:
      - id: pyupgrade
        args: [--py36-plus]

  # - repo: local
  #   hooks:
  #     - id: pytest-check
  #       name: pytest-check
  #       entry: poetry
  #       args: ["run", "pytest", "-s", "-x", "-vv", "tests"]
  #       language: system
  #       pass_filenames: false
  #       always_run: true

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.4
    hooks:
      - id: ruff
